
module MyModule
using PyPlot

export f


function f(x::Float64)
	println("Float version of f")
end

function f(x::Int64)
# Calculate maxium of matrix generated by y(x)
	A = y(x)
	m = maximum(A)
	return m
end

function y(n)
# Generate random matrix of dimension n x n x n
	return rand(n,n,n)
end



end

